language: python
python: "3.6"

script: python setup.py bdist_wheel

deploy:
  - provider: pypi
    user: miterion
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      tags: true
    password:
      secure: "guxnUHCaHXWd+5vz8+tTjHGi1aoaiD8Cdb5Zs7R4fBCTr50xUPQzGE3oIv1sQmBVIChvcuoitsYk9m2gqHuL7tHLB4hi2Ubat+6z2z6pQQ0t4LkjJGZgkFPlHP4p/mgsMlL2al5LDsi4rNNp3R8h6zZyC2M5wpdsBXtQxKoCBwvFDFllDYryBeZTZ73UlBaJTlKrc3Y5wkrXIVYEAfCydysT3+k4R8k5qibqaTfBOCFvA9I4LAZ7mjddQwD89v4sGeROjfZT1zJ2xhHglgeCilmdq1Sey3QZ8CiWKMCyOmXPyM7JqBP2nauKeA9QSv13jiyJjYtGXJIPvtuI297GE1PqE+L9VCJaBvTetvr9AHT7OfBBewFNb3y2VeeBcvDwYCWbGa0uuo7s3QmLjcZazYVs6QFIW9UMVeBseEtvWK10t6FCF9o2Xv1SNadB6PsWGcuKFkPOEAl2ws39ZWP9FXlYB0C3VHvrIhiXtwwH7K8T6HzpSaiTfh5Npz01kmBuX1bFyJxoYpYM2X9bx32ruO//PyZCXEkwag8BWNCo501hF+XYtdTpxQmF/amPyfaLqIDmvbCbLvNpGxHgWSo0VRMgcFoiQ1vIRuXCzftRO+2ly8+pBhe9z1b8nP6tVdFxCPEZg4nhtKwGXx/QSlptHK2UCy3daB5GdL7C2YlaDDc="
  - provider: releases
    file_glob: true
    file: dist/*
    on:
      tags: true
    api_key:
      secure: m+2ldXYPDQ7meYQr15IsVdktAc4WTS2tMAJOUGfD77tD54D5Hp2cw0NMyenpYYuDoJXEnZcpYUOKjJZWKh3vC8eOpiDFdlFjuxTNmXku4dDxInaglHyi+TCJeP3wOXix9ld9XCxjNh7A9ET5tEaD58ztc14iK18acJ07MDHJYC2JKjEh2xs6hVW+T6XxX7maenMCYp4yKhMPBUFkqlHK7PB7GoPIBAU86NOcplDUgAg9T0EFyIKmoViUFobjDPBEuVixV7UPZ565HlKj3HCp/eKz4mZXtGjl1rGw07JZ/0F7iB17I99LVRPtPWtRCunpsc4KE0deThU+H9azxxpnl/y/UMxBirET1SjRofp1rWC/RVwY13PzIuVJrNsWZDPQUaMh1jKPmu5j1ZKp+5NSrLndHn15gSlaC4SUeKsG3C1MksKyj+vubNeSPP7PKHRul+sfjE6QgY9b7EbLHUNM7kmQrT1PcKZYmCjyVL3jwK3z4KqhSYEKxaqkJ2dM0JNlPPUEf6qEhDtvaqYSXXtSlLG2rtS0nCsp8DF+nuHCLC56vIQEOFdRvW0h6DJOY8vUln1lKnnnN4EzT1J8laxceEq1tvtw/HDE0JKTACG5nR3S700ZUqHNDvlQwwq9L36zDwX0hogHbYPSt1IGPBtCjnEem5fzySugNI/huj6kxqg=
    
