language: python
python: "3.7"

install:
  - pip install yapf

script: 
  - yapf -qrp dfngen
  - python setup.py bdist_wheel

deploy:
  - provider: releases
    file_glob: true
    file: dist/*.whl
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "m+2ldXYPDQ7meYQr15IsVdktAc4WTS2tMAJOUGfD77tD54D5Hp2cw0NMyenpYYuDoJXEnZcpYUOKjJZWKh3vC8eOpiDFdlFjuxTNmXku4dDxInaglHyi+TCJeP3wOXix9ld9XCxjNh7A9ET5tEaD58ztc14iK18acJ07MDHJYC2JKjEh2xs6hVW+T6XxX7maenMCYp4yKhMPBUFkqlHK7PB7GoPIBAU86NOcplDUgAg9T0EFyIKmoViUFobjDPBEuVixV7UPZ565HlKj3HCp/eKz4mZXtGjl1rGw07JZ/0F7iB17I99LVRPtPWtRCunpsc4KE0deThU+H9azxxpnl/y/UMxBirET1SjRofp1rWC/RVwY13PzIuVJrNsWZDPQUaMh1jKPmu5j1ZKp+5NSrLndHn15gSlaC4SUeKsG3C1MksKyj+vubNeSPP7PKHRul+sfjE6QgY9b7EbLHUNM7kmQrT1PcKZYmCjyVL3jwK3z4KqhSYEKxaqkJ2dM0JNlPPUEf6qEhDtvaqYSXXtSlLG2rtS0nCsp8DF+nuHCLC56vIQEOFdRvW0h6DJOY8vUln1lKnnnN4EzT1J8laxceEq1tvtw/HDE0JKTACG5nR3S700ZUqHNDvlQwwq9L36zDwX0hogHbYPSt1IGPBtCjnEem5fzySugNI/huj6kxqg="
  - provider: pypi
    user: miterion
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      tags: true
    password:
      secure: "n5mGET4Wl3pQgoSIytuUumJWZ2uMii2p8QjnKqKfenra5xomuFhcqGVOXHbNTrEpCOYKlDQW8/ZkNDYloV+1AuDgkFUg6ZlitPfwLEx3b0dXKO8/7kx/vszqQq9Jvchw04tWL//B2iqe6L4qBzCE/W/3zARXCijfMelzinxLJrLI8T3McYf7aztBI48yOduEi+UDXO+HL+YH4nQIJ+iNpuvU6Uq/UcHyo1lqd6ZVayx0UTBLh7zmwwhh5qAV+BQ7ERaAdcjpvjfmIARVqBrsv5+FksbcnlHs6awakNQdWD65jcahaWZwNTsQWi2sE+UJwRG6fnanSmAKJSD0jRPbH5Dva2WShd/DczmYOh8J5VsXW55rkANx76VU8aqLx4mOdQ/QtkwZIuPRnxNYt9/9G8ZaewozpP76kBBw+I8+0MfvyWyjO6SwxPEhijamezSY7TGad93H7z/CDaOCr5DBfdxYgFctmH0bi6LoaowElNCCkie8tbe4vaNVyEkuEi+8z0c3kcMXroL2x13dZ3w5cFRZwsphSqB/nGCHJSy85fc2kNAM/JGmHLEPSkZNwMDNbR0UBLVzlnjdc0d+HFEgwatXKVT6sYawNX0GWKKQZGWaWfx+IIKzi67q08G4xrvmTwhOTo2Bwg0hKwtCZT9XVCPftZGJyflZnqQanlM8eQs="
