language: python
python: "3.6"

script: python setup.py bdist_wheel

deploy:
  - provider: pypi
    user: miterion
    on:
      tags: true
    skip_cleanup: true
    password:
      secure: clraIbEEem2AKWRkRBHtUqTRaNeIb9RJDvGmlyAzSc07Dq+BArEh7aDimY41RpR5vF/jSiaQyt600NEeuySPE04qKCeSUc4+GukO6DDknosJoU3xx5PRM1A+UvVUrrNPJnZrrKKGdy4onJ7YzO11x/9k9jqVIwiWRQuiGkXPV/GTrDAN8fx/7EDNNmMkE0PfFfSoQUw/XFEuC3ilXne+wctpYVkYWf6ibpIAuufGcLbauOdSjraROdllEWYTw0brSgMaffEtOVFgyHHsiKS4AzLDFgDPF3Ns2lhu4UFPkHu+uHYWyRKMtLIiovZ09dFOoTyYtnEAkFJy+N+Yk6Od/RBTiwxIrvzu7LPPC3bXO70lxnBjly7P6jBb2/7QxoQvu2kYyd9dnpUDDKi8R9wvJrrcfhZuok+pBxKGlofcnxuvSm2ItjI7LykpNVWwZi7Aj+iAF5zWh0163WGZvxQ/Apv/16NvRlbZmEUsAks6XZ2pd0zRXTgNSNewOQfbDzYjRbhVFc/DaWsHbqKLitAHac1n8O7gWVqhT3S8TYOi9uoB6qtemoebXBu3ojWFYv1WPZNdMij8m0GJQQ4H8B5KA4ThJheusSuOEZF4KiQ67jlJZ4RESWaIXpEgZTjU/JLYb3Z3/HZ5kr/e92R1/48lzYs5vH0R406xfVnBBlRuH+o=
  - provider: releases
    file: dist/*
    file_glob: true
    on:
      tags: true
    api_key:
      secure: m+2ldXYPDQ7meYQr15IsVdktAc4WTS2tMAJOUGfD77tD54D5Hp2cw0NMyenpYYuDoJXEnZcpYUOKjJZWKh3vC8eOpiDFdlFjuxTNmXku4dDxInaglHyi+TCJeP3wOXix9ld9XCxjNh7A9ET5tEaD58ztc14iK18acJ07MDHJYC2JKjEh2xs6hVW+T6XxX7maenMCYp4yKhMPBUFkqlHK7PB7GoPIBAU86NOcplDUgAg9T0EFyIKmoViUFobjDPBEuVixV7UPZ565HlKj3HCp/eKz4mZXtGjl1rGw07JZ/0F7iB17I99LVRPtPWtRCunpsc4KE0deThU+H9azxxpnl/y/UMxBirET1SjRofp1rWC/RVwY13PzIuVJrNsWZDPQUaMh1jKPmu5j1ZKp+5NSrLndHn15gSlaC4SUeKsG3C1MksKyj+vubNeSPP7PKHRul+sfjE6QgY9b7EbLHUNM7kmQrT1PcKZYmCjyVL3jwK3z4KqhSYEKxaqkJ2dM0JNlPPUEf6qEhDtvaqYSXXtSlLG2rtS0nCsp8DF+nuHCLC56vIQEOFdRvW0h6DJOY8vUln1lKnnnN4EzT1J8laxceEq1tvtw/HDE0JKTACG5nR3S700ZUqHNDvlQwwq9L36zDwX0hogHbYPSt1IGPBtCjnEem5fzySugNI/huj6kxqg=
    
